version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/blog-back-spring
    overwrite: yes
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 60
      runas: root